### ISSUE TITLE
Torque arm needs recalibration

### ISSUE THREAD

**Issue by petebachant** [UNH-CORE/turbine-test-bed#2]
Need to determine how many steps to use. For their NIST traceable calibration, Interface uses 8; 6 ascending and 2 descending.

**Comment by wosnik** [comment]
6 ascending sounds good.
I would consider 2 descending a minimum, might be better to do a couple more.

**Comment by petebachant** [comment]
I also need to decide on how long to sample at each load. I will be recording at 2 kHz, and was thinking 30 seconds. If each sample is independent, we wouldn't gain much in terms of confidence interval on the mean by sampling twice as long. 

![image](https://cloud.githubusercontent.com/assets/4604869/5795505/657dd4a4-9f5f-11e4-99fa-758346a1db8a.png)

**Comment by petebachant** [comment]
Calibration to be committed:

![image](https://cloud.githubusercontent.com/assets/4604869/5848718/a105f8de-a1a9-11e4-8285-c1af28f2fa06.png)
